# Generated by Django 5.2.7 on 2026-05-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_workouttracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
