# Generated by Django 6.0.5 on 2026-05-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_workouttracker_date_alter_workouttracker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttracker',
            name='date',
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='days',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=5),
        ),
    ]
