# Generated by Django 6.0.5 on 2026-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_workouttracker_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttracker',
            name='days',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=5),
        ),
    ]
